os: osx
osx_image: xcode11.2
language: node_js
node_js:
- 11
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_script:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then chmod +x add-osx-cert.sh; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then ./add-osx-cert.sh; fi
script:
- yarn install
- yarn package
- yarn make --skip-package
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Y4IWZbYSqJ9YqDBDLn1+OoBATrWaqDt9C5rqRZD8CWTWtR1Tkmu1NGiJAKCAohbOQOjbztyFWEddDsCo0bWrXRuEJv+H26YK1ilQEWq1hpOg5ats7mowX39XYIpJk9hrCHqGqsecYnWMH492Hx0BbBq96ogZGKNrzKdir2JSzEDg4/RZCAJlcVuB2l+z7QJ0WtT+E3oRjXzJv+UEHykA+9IuarIQQqKn/mbEYTD+nnMOBR+QGVD3Wk4JUfGVr2WkvFxfPafw9LE5ke2tkAGiGMC4+wFVObqM1rT1LEuA7ENTX9l9txuP+El4HEuOk97PhjW0+huasFlvfcK9l2NMmeXQYIRB63TUsduirB95GxS+h8QY1D50eaEPcJqSItsF3wy/oQnrG4zei8fKWI0o+XH2YUFrlUjHspvOtWWvWxKLf3NhS6zwV7OcPv+LoaVr0CLkkf46vW/UtjVyhNWz4SuEgEBBSybBL3KPiF/01h0aql9MlPRNSHneyPQWePPXkwJSEFghMFfJAD6ktVjd+UdHjn5deGGakg2WoRrvF8WsD81jIebeIrXgDjcnfaU3fbnWIz6BqeJNWaTVvy9knyZf2Z5VHNtUsgG9s7W01NP0vtIgFeJi8G4aau/NacRlQ/Oo1WnG9H6a49yjokCdmIF/DCrd9yR8wXgNSY4gO/o=
  file: out/make/zip/darwin/x64/*
  file_glob: true
  on:
    repo: heilerich/actualmoney
    tags: true
notifications:
  email: false
  pushover:
    on_success: always
    on_failure: always
    users:
      secure: LiAQKBx2lcXAU/FJYoof0UrH7U1RvNbkkPh70J/1UQsqqzEofE3LBU9Qd0U8N2uHTOfyq0cODWqDYXf4dv4tjuJ1Owt9rNZ7PwtZ+dQ81UWku9CbnSgB7A0V5sZ/jxQaEdmgOvNhyYrLYA5xvcTPYp4OCE2vNE6S6Z5XHSdMjQU/H2mVilaxKeUGJoP+fvWncmruFW/MzIrJmeoTNU1sRXRlkh4Dt6KPgDnf4yuS0gz3XNGYTBSg6vLqTHXBE9lasSEYwHBf9dAhAPjdC+69eoD8Gxt38G6vfilV97rO+75lh+PbWzFyjQ7q/kReol8k3nrfyByKNmtUhFp/YhSl77D6+Zx15WhMuSjazETbs24RS/fn+sDv8kpdtuAo4dUBLp1XZU3zf1lGIZYCMAEQqPNmOG4kgR2ZuJlvgNGJSZkDVkvtSOfab80Tz14xsjePpfirYeC6UiozNizfe25ph3WB5e+6Bbcqmu1TeIkMWC4TOElwpGLP/lZQmSAkzCS8aqFWhih5uK1vrz8IQ0gzLxfs+BAvUF+KfFI8l2F/8DvLr7ZUwfhFbR3mAUDaOIwJD7+eKe5RVpI8HCApSDo+l4ev7mOApVwlIIyt9a6k3E92IWCMA9cZC1wjeYWwpaPN9E9eEZa1jM3mTQv+dDx4Z2yLh1wS/+4MsJMGQFaA/4M=
    api_key:
      secure: aGXMYy1CUaN6kdCNpHjKZgEBcK6GKJjx/sjyl9u79yxZKxn9gSoOK0Wt58GNxHeGVkDKisyDGROvlPOKHDTxa94vabRw7eOlrOHherp+pKDVuFxIdLIKll11GtoeowF1t4fgMeV7V+DoZY8bNeqRaHJzcOK4db9spVsaeoEpkGG40c/2Vn8VzufZW42QoqxpTeRlN0XJIS+QuSPdrHOrofWZI3of8MLn0yXe4EksyY1OwXJkNNxq5Ww4oWkpcbNcsl8QUqzJUibphc+EnjMPVY7Nv3eZGn8Qbpw/HSz/HqJQVIh/Z4e838eXUPplkphn9McISQ0FiJwZ8VFaTppq6Ju0qBKZhx1F9qy6yM8PRLh+L6wLc3PqmYzHvb1DGiu6QKvEoX+MPWw52fHE0mu0f/kK1DhyKI7bBMku3eN8CWUjBsG8VKLa0hL15XvJm42C085/ZTH9/3xgkPBhor/xy2z8unsLkORhMJrB+P8cu54/9a6Jzx+9jcGlcYeo7t5Xd89PLJtwrupTIy+vNJcLIOQQpHjN0uOvwFGx/E1DrJSWojXSWj6Sl60R4Xdu0CPYETuIqAOoHzGSesAWyS0/rThfVyVuWIWOkM8EIzzn17H5MxBB/1MKVtxcdWGA94GFKd5359OdTEIxDFmrG5cY/AIqicpntx9ZM1gFfUv6oXw=
