os: osx
language: node_js
node_js:
  - 11
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
install:
- brew install yarn
script:
- yarn install
- yarn package
- yarn make --skip-package
deploy:
  provider: releases
  api_key:
    secure: Y4IWZbYSqJ9YqDBDLn1+OoBATrWaqDt9C5rqRZD8CWTWtR1Tkmu1NGiJAKCAohbOQOjbztyFWEddDsCo0bWrXRuEJv+H26YK1ilQEWq1hpOg5ats7mowX39XYIpJk9hrCHqGqsecYnWMH492Hx0BbBq96ogZGKNrzKdir2JSzEDg4/RZCAJlcVuB2l+z7QJ0WtT+E3oRjXzJv+UEHykA+9IuarIQQqKn/mbEYTD+nnMOBR+QGVD3Wk4JUfGVr2WkvFxfPafw9LE5ke2tkAGiGMC4+wFVObqM1rT1LEuA7ENTX9l9txuP+El4HEuOk97PhjW0+huasFlvfcK9l2NMmeXQYIRB63TUsduirB95GxS+h8QY1D50eaEPcJqSItsF3wy/oQnrG4zei8fKWI0o+XH2YUFrlUjHspvOtWWvWxKLf3NhS6zwV7OcPv+LoaVr0CLkkf46vW/UtjVyhNWz4SuEgEBBSybBL3KPiF/01h0aql9MlPRNSHneyPQWePPXkwJSEFghMFfJAD6ktVjd+UdHjn5deGGakg2WoRrvF8WsD81jIebeIrXgDjcnfaU3fbnWIz6BqeJNWaTVvy9knyZf2Z5VHNtUsgG9s7W01NP0vtIgFeJi8G4aau/NacRlQ/Oo1WnG9H6a49yjokCdmIF/DCrd9yR8wXgNSY4gO/o=
  file: out/make/zip/darwin/x64/*
  file_glob: true
  on:
    repo: heilerich/actualmoney
    tags: true
notifications:
  email: false